# https://learn.netlify.app/en/basics/

defaultContentLanguage: 'en'
defaultContentLanguageInSubdir: true
showVisitedLinks: false

canonifyURLs: true
enableGitInfo: true

title: 'F60.31'

outputs:
  home:
    - HTML
    - JSON

theme: 'hugo-theme-learn'
params:
  themeVariant: 'blue'
  titleSeparator: "-"
  disableMermaid: true
  disableNextPrev: true

languages:
  en:
    title: 'Emotionally unstable personality disorder (EUPD)'
    description: 'This is a wiki with resources about the emotionally unstable personality disorder.'
    languageCode: 'en-us'
    landingPageURL: '/en'
    weight: 1
    languageName: "English ðŸ‡¬ðŸ‡§"
    menu:
      shortcuts:
        - name: <i class='fab fa-github'></i> Contribute to this wiki
          url: https://github.com/deeplyrouted/bpdwiki/issues
          weight: 0
        - name: <i class='fab fa-reddit'></i> r/BPD
          url: https://reddit.com/r/bpd
          weight: 1
        - name: <i class='fab fa-reddit'></i> r/BPDlite
          url: https://reddit.com/r/bpdlite
          weight: 1
        - name: "<i class='fa fa-briefcase-medical'></i> Australia"
          url: https://www.uow.edu.au/project-air/find-a-service/
          weight: 2
        - name: "<i class='fa fa-briefcase-medical'></i> USA"
          url: https://www.uow.edu.au/project-air/find-a-service/
          weight: 2
        - name: "<i class='fa fa-briefcase-medical'></i> France"
          url: https://www.unafam.org/troubles-borderline
          weight: 2
        - name: "<i class='fa fa-briefcase-medical'></i> United Kingdom"
          url: http://borderlinesupport.org.uk/
          weight: 2
        
  de:
    title: 'Emotional-instabile PersÃ¶nlichkeitsstÃ¶rung (EUPD)'
    description: 'Das ist ein Wiki mit Ressourcen Ã¼ber die emotional-instabile PersÃ¶nlichkeitsstÃ¶rung.'
    languageCode: 'de-de'
    weight: 2
    languageName: "Deutsch ðŸ‡©ðŸ‡ª"
    landingPageURL: '/de'
    menu:
      shortcuts:
        - name: <i class='fab fa-github'></i> Zum Wiki beitragen
          url: https://github.com/deeplyrouted/bpdwiki/issues
          weight: 0
        - name: <i class='fab fa-reddit'></i> r/BPD
          url: https://reddit.com/r/bpd
          weight: 1
        - name: <i class='fab fa-reddit'></i> r/BPDlite
          url: https://reddit.com/r/bpdlite
          weight: 1
        - name: <i class='fa fa-briefcase-medical'></i> therapie.de
          url: https://www.therapie.de/therapeutensuche/
          weight: 2
